server:
  port: 10010
spring:
  application:
    name: api-gateway-lsw
zuul:
  routes:
    user-service-lsw: # 这里是路由id，随意写
      path: /user-service-lsw/** # 这里是映射路径
      url: http://127.0.0.1:8081,http://127.0.0.1:8083 # 映射路径对应的实际url地址
